name: Create package
run-name: Release ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
                include:
                - os: windows-latest
                  binary_name: pdfmerger.exe
                  archive_name: pdfmerger-windows.zip
                - os: macos-latest
                  binary_name: pdfmerger
                  archive_name: pdfmerger-mac.zip
                - os: ubuntu-latest
                  binary_name: pdfmerger
                  archive_name: pdfmerger-linux.zip
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Verify branch is main
          shell: bash
          run: |
            if ! git branch -r --contains ${{ github.sha }} | grep -q "origin/main"; then
              echo "[ERROR] This tag wasn't created on branch 'main'! Cancelling build."
              exit 1
            fi
            echo "[OK] Tag is on branch 'main'. Continue build."

        # TODO build steps
        
        - name: Create ZIP archive (Windows)
          if: matrix.os == 'windows-latest'
          run: Compress-Archive -Path dist/${{ matrix.binary_name }} -DestinationPath dist/${{ matrix.archive_name }}

        - name: Create ZIP archive (Linux / macOS)
          if: matrix.os != 'windows-latest'
          run: |
            cd dist
            zip ${{ matrix.archive_name }} ${{ matrix.binary_name }}

    release:
      name: Create GitHub Release
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download all artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: assets-*
            merge-multiple: true

        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              pdfmerger-windows.zip
              pdfmerger-mac.zip
              pdfmerger-linux.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}